# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/paul/Desktop/archcomp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/paul/Desktop/archcomp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paul/Desktop/archcomp/CMakeFiles /home/paul/Desktop/archcomp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/paul/Desktop/archcomp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lab1

# Build rule for target.
lab1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lab1
.PHONY : lab1

# fast build rule for target.
lab1/fast:
	$(MAKE) -f lab1/CMakeFiles/lab1.dir/build.make lab1/CMakeFiles/lab1.dir/build
.PHONY : lab1/fast

#=============================================================================
# Target rules for targets named sc

# Build rule for target.
sc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sc
.PHONY : sc

# fast build rule for target.
sc/fast:
	$(MAKE) -f lab1/CMakeFiles/sc.dir/build.make lab1/CMakeFiles/sc.dir/build
.PHONY : sc/fast

#=============================================================================
# Target rules for targets named lab2

# Build rule for target.
lab2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lab2
.PHONY : lab2

# fast build rule for target.
lab2/fast:
	$(MAKE) -f lab2/CMakeFiles/lab2.dir/build.make lab2/CMakeFiles/lab2.dir/build
.PHONY : lab2/fast

#=============================================================================
# Target rules for targets named term

# Build rule for target.
term: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 term
.PHONY : term

# fast build rule for target.
term/fast:
	$(MAKE) -f lab2/CMakeFiles/term.dir/build.make lab2/CMakeFiles/term.dir/build
.PHONY : term/fast

#=============================================================================
# Target rules for targets named lab3

# Build rule for target.
lab3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lab3
.PHONY : lab3

# fast build rule for target.
lab3/fast:
	$(MAKE) -f lab3/CMakeFiles/lab3.dir/build.make lab3/CMakeFiles/lab3.dir/build
.PHONY : lab3/fast

#=============================================================================
# Target rules for targets named bc

# Build rule for target.
bc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bc
.PHONY : bc

# fast build rule for target.
bc/fast:
	$(MAKE) -f lab3/CMakeFiles/bc.dir/build.make lab3/CMakeFiles/bc.dir/build
.PHONY : bc/fast

#=============================================================================
# Target rules for targets named lab4

# Build rule for target.
lab4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lab4
.PHONY : lab4

# fast build rule for target.
lab4/fast:
	$(MAKE) -f lab4/CMakeFiles/lab4.dir/build.make lab4/CMakeFiles/lab4.dir/build
.PHONY : lab4/fast

#=============================================================================
# Target rules for targets named rk

# Build rule for target.
rk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rk
.PHONY : rk

# fast build rule for target.
rk/fast:
	$(MAKE) -f lab4/CMakeFiles/rk.dir/build.make lab4/CMakeFiles/rk.dir/build
.PHONY : rk/fast

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) -f Main/CMakeFiles/Main.dir/build.make Main/CMakeFiles/Main.dir/build
.PHONY : Main/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lab1"
	@echo "... sc"
	@echo "... lab2"
	@echo "... term"
	@echo "... lab3"
	@echo "... bc"
	@echo "... lab4"
	@echo "... rk"
	@echo "... Main"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

